### PR TITLE
Refactor all the things

### PR DESCRIPTION
**Pull request by kolbyjack**
I'm not sure if you'll want to take this, as it changes nearly everything about the look of the widget, but I figure I should offer it.  The diff is huge, but adding ?w=1 at the end of the diff url makes it ... slightly ... more readable.

- Add entries for focus_on teams that don't have a game scheduled today
  - TODO: Get record for teams without a game today
- Create individual widget types for pregame, ingame, postgame, postponed game, and no game
  - Pregame: Show start time and propable pitchers
  - In game: Show inning state, runners on base, count, outs, pitcher, and batter
  - Postgame: Show R/H/E, winning pitcher, losing pitcher, and save pitcher
  - Postponed game: Show reason for postponing (if known)
  - No game: Explicitly show that the focus_on team doesn't have a game today
- Replace tabs with spaces to avoid weird formatting based on tab settings
- Convert MMM-MLB.js to unix line endings
- Set self at top of functions and use it instead of this

### CODE REVIEW

**Comment by cowboysdude** [comment]
Well I will check it out when I get home.  If it makes it a better module
I'll probably like it 😁

**Comment by cowboysdude** [comment]
Great changes, Thank you!!!!!!!!!!!!!!

**Comment by kolbyjack** [comment]
Thanks, though I'm rethinking whether the module should create the fake games when a team doesn't have a game scheduled.  It was nice to make sure I hadn't just broken something during development, but it'll probably be somewhat annoying in practice, especially during the offseason.  I may open a PR eventually to remove that part, or at least make it optional.

**Comment by cowboysdude** [comment]
Well I'll keep my eyes open if you do.  I think it looks great.  I've not
had time to change anything other then the weather module lol.   That alone
keeps me busy.

**Pull request merged**
